version : '2'
services:
  ngtesting-redis:
    image: registry.cn-shanghai.aliyuncs.com/aaron-share/redis
    ports:
    - "56379:6379"

  ngtesting-postgres:
    image: registry.cn-shanghai.aliyuncs.com/ngtesting/ngtesting-postgres:2.0.0
    environment:
    - POSTGRES_PASSWORD=P2ssw0rd
    ports:
    - "55432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  ngtesting-web:
    image: registry.cn-shanghai.aliyuncs.com/ngtesting/ngtesting-web:2.0.0
    depends_on:
    - ngtesting-postgres
    - ngtesting-redis
    ports:
    - "50080:80"
    command: sh /launch.sh
