version : '2'
services:
  ngtesting-postgres:
    image: registry.cn-shanghai.aliyuncs.com/ngtesting/ngtesting-postgres:2.0.0
    environment:
      - POSTGRES_PASSWORD=P2ssw0rd
    ports:
      - "55432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  ngtesting-web:
    image: registry.cn-shanghai.aliyuncs.com/ngtesting/ngtesting-web:2.0.0
    depends_on:
      - ngtesting-postgres
    ports:
      - "58080:8080"
    command: sh /launch.sh
