version : '2'
services:
  ngtesting-mysql:
    image: ngtesting/mysql:latest
    volumes:
      - ./src/main/docker/mysql/my.cnf:/etc/mysql/my.cnf /mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P2ssw0rd
    ports:
      - "53306:3306"
    expose:
      - "53306"

  ngtesting-web:
    image: ngtesting/web:latest
    ports:
      - "58080:8080"
    links:
      - ngtesting-mysql
